### ISSUE TITLE
Azure gov cloud locations don't match in latest failoverProvider.js

### ISSUE THREAD

**Issue by edwoodjrjr** [F5Networks/f5-cloud-libs-azure#10]
When the Azure gov location is "usgovvirginia", this bit of code is not matching "usgov", causing the failover script to incorrectly use the public cloud suffix:

https://github.com/F5Networks/f5-cloud-libs-azure/blob/6cd369dfdc552d40c71ff085e1ef7e9a0e77d904/scripts/failoverProvider.js#L178

This worked in v2.5.0 of f5-cloud-libs-azure:

https://github.com/F5Networks/f5-cloud-libs-azure/blob/22002c40f8980aa39bbd27fc4f47acd54bfa5d21/scripts/failoverProvider.js#L168

**Comment by edwoodjrjr** [comment]
Tracking with internal issue 930.

**Comment by namhly** [comment]
This bug has been fixed in v2.8.0.
I will close this issue. Thanks.
