### ISSUE TITLE
Enhancement: failoverProvider.js: matchRoutes on multiple interfaces

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-cloud-libs-azure#3]
Currently failoverProvider.js will only update UDR to reference the internal interface.  It would be useful to also support the external interface as well.
```
Route 1 -> External Interface - [ BIG -IP ] - Internal Interface <- Route 2
```

**Comment by edwoodjrjr** [comment]
Will have to find a way to correlate interface with route.  Most likely it will be another Azure tag on the route table.

**Comment by jsevedge** [comment]
This has been resolved, closing.
